# Generated by Django 5.2.6 on 2025-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='mediafiles/default_profile_picture.jpg', upload_to='mediafiles/profile_pictures'),
        ),
    ]
