# Generated by Django 5.2.6 on 2025-10-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile_picture.jpg', upload_to='profile_pictures'),
        ),
    ]
