# Generated by Django 5.2.6 on 2026-01-10 19:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='host_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='host_status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='INACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='valid_id',
            field=models.ImageField(blank=True, null=True, upload_to='ids'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, null=True, region=None),
        ),
    ]
