#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate
python manage.py migrate django_celery_beat
python manage.py runserver 0.0.0.0:8000
# gunicorn booking_site.wsgi:application --bind 0.0.0.0:8000