# Generated by Django 5.2.6 on 2025-10-16 09:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertylike',
            unique_together={('property', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyview',
            unique_together={('property', 'ip_address')},
        ),
    ]
