# Generated by Django 5.2.6 on 2025-12-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_reservation_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='checkin_time',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AddField(
            model_name='property',
            name='checkout_time',
            field=models.TimeField(default='11:00'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_instant_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
