# Generated by Django 5.2.6 on 2025-10-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='/uploads/properties/default_property.png', upload_to='uploads/properties'),
        ),
    ]
