# Generated by Django 5.2.6 on 2025-12-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_checkin_time_property_checkout_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkin_time',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkout_time',
            field=models.TimeField(default='11:00'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_instant_booking',
            field=models.BooleanField(default=False),
        ),
    ]
