# Generated by Django 5.2.6 on 2025-12-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_reservation_checkin_time_reservation_checkout_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_code',
            field=models.CharField(blank=True, editable=False, max_length=16, unique=True),
        ),
    ]
