# Generated by Django 5.2.6 on 2025-12-03 07:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='property',
            name='service_fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.03'), max_digits=4),
        ),
        migrations.AddField(
            model_name='property',
            name='weekly_discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='reservation',
            name='long_stay_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.03'), max_digits=4),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
