# Generated by Django 5.2.6 on 2025-12-03 13:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_cleaning_fee_property_monthly_discount_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
