# Generated by Django 5.2.6 on 2025-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertytag_property_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytag',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
