# Generated by Django 5.2.6 on 2025-12-03 14:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_reservation_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='monthly_discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='property',
            name='weekly_discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=4),
        ),
    ]
