# Generated by Django 5.2.6 on 2025-12-13 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_propertytag_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertyview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='propertyview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propertyview',
            index=models.Index(fields=['user', 'property'], name='properties__user_id_33be98_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyview',
            index=models.Index(fields=['ip_address', 'property'], name='properties__ip_addr_0b8927_idx'),
        ),
    ]
