# Generated by Django 5.2.6 on 2025-12-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_propertyview_unique_together_propertyview_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
