# Generated by Django 5.2.6 on 2025-12-16 18:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
    ]
