from django.urls import path

from .views import (
    PropertyListView,
    PropertyDetailView,
    PropertyCreateView,
    PropertyUpdateView,
    PropertyDeleteView,
    ReservationListCreateView,
    ReservationDetailView,
    ReservationListProperty,
    ReservationHostListView,
    PendingReservationListView,
    ApproveReservationView,
    DeclineReservationView,
    UserFavoritesView,
    ToggleFavoriteView,
    PropertyTagListView,
    PropertyStatusUpdateView,
)
urlpatterns = [
    path('', PropertyListView.as_view(), name='property-list'),
    path('<uuid:property_id>/', PropertyDetailView.as_view(), name='property-details'),
    path('create/', PropertyCreateView.as_view(), name='property-create'),
    path('<uuid:property_id>/update/', PropertyUpdateView.as_view(), name='property-update'),
    path('<uuid:property_id>/delete/', PropertyDeleteView.as_view(), name='property-delete'),
    path('reservation/', ReservationListCreateView.as_view(), name='reservation-list-create'),
    path('reservation/<uuid:reservation_id>/', ReservationDetailView.as_view(), name='reservation-details'),
    path('reservation/requests/', PendingReservationListView.as_view(), name='reservation-requests'),
    path('<uuid:property_id>/reservation/', ReservationHostListView.as_view(), name='reservation-host-property'),
    path('reservation/host/', ReservationHostListView.as_view(), name='reservation-host'),
    path('reservation/<uuid:reservation_id>/approve/', ApproveReservationView.as_view(), name='reservation-approve'),
    path('reservation/<uuid:reservation_id>/decline/', DeclineReservationView.as_view(), name='reservation-decline'),
    path('likes/', UserFavoritesView.as_view(), name='user-favorites-list'),
    path('reservation/p/<uuid:property_id>', ReservationListProperty.as_view(), name='reservation-list-property'),
    path('<uuid:property_id>/toggle-favorite/', ToggleFavoriteView.as_view(), name='toggle-favorite'),
    path('tags/', PropertyTagListView.as_view(), name='tag-list'),
    path("<uuid:property_id>/status/", PropertyStatusUpdateView.as_view(), name="property-status-update",),
]