import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import StoreProvider from "./StoreProvider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Navbar from "./components/navbar/Navbar";
import { InitUser } from "./users/InitUser";
import Loading from "./components/common/Loading";
import { ConfigProvider } from "antd";
import NavbarMobile from "./components/navbar/NavbarMobile";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: "#7289DA",
            fontFamily:
              "var(--font-inter), -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
          },
        }}
      >
        <body className={`${inter.className} antialiased`}>
          <StoreProvider>
            <AntdRegistry>
              <Loading />
              <InitUser />
              <Navbar />
              <div>{children}</div>
              <div className="sm:hidden">{/* <NavbarMobile /> */}</div>
            </AntdRegistry>
          </StoreProvider>
          <ToastContainer
            position="bottom-right"
            autoClose={3000}
            newestOnTop={false}
            closeOnClick={false}
            hideProgressBar={true}
            pauseOnFocusLoss
            pauseOnHover
            theme="light"
          />
        </body>
      </ConfigProvider>
    </html>
  );
}
