# Generated by Django 5.2.6 on 2025-09-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
